grpc:
  client:
    user-service:
      address: static://localhost:6565
      negotiationType: plainText
    movie-service:
      address: static://localhost:7575
      negotiationType: plainText

rest:
  user-service-url: http://localhost:6666
  movie-service-url: http://localhost:7676
